// Generated by CoffeeScript 1.6.2
var RecipeController;

RecipeController = function($scope, $http, $log) {
  $scope.ingredients = [];
  $scope.steps = [];
  return $http.get('../data/json.txt').success(function(data, status, headers, config) {
    if (data && status === 200) {
      $scope.ingredients = data[0];
      return $scope.steps = data[1];
    }
  });
};
